### ISSUE TITLE
Comment/help

### ISSUE THREAD

**Issue by wied03** [puddly/casserole#1]
@puddly - Have you looked @ https://github.com/GEMakers/gea-plugin-water-heater/blob/master/hewh-interface.docx ? Different appliance but might help. I analyzed a GE connect's communication with my water heater but I hadn't yet figured out 19200 baud/inverted so thanks for that piece of info.

**Comment by puddly** [comment]
@wied03 I have not, thanks for the document. All of those commands and responses seem to be implemented on top of the base layer that I'm almost done figuring out so I think replacing the USB adapter will not make the main [`gea-plugin-water-heater`](https://github.com/GEMakers/gea-plugin-water-heater/) module work any differently.

**Comment by wied03** [comment]
I've since found that the GE connect module does not adhere to that guide
at all. It instead follows write read commands like the SDK and your readme
mentioned. I took apart the ERD data and it worked like the SDK did.

I need to figure out the hash as well. Maybe it's just a simple checksum
like ipv4 uses?

sent from my mobile device

**Comment by puddly** [comment]
@wied03 I've updated the README a few times, including a description of the checksum. It's implemented in the Python script that parses the packets.
