### ISSUE TITLE
RJ45 pinout?

### ISSUE THREAD

**Issue by Zebble** [puddly/casserole#5]
Is the RJ45 pinout documented anywhere?

It was a mentioned that one of the issues with communication is not knowing/being able to control who has control of the bus, which results in colliding/lost messages.  Any chance there might be some sort of flow control going on on other pins on the RJ45?

**Comment by puddly** [comment]
The RJ45 connector, at least on my machine, physically has only three populated pins: 9V, GND, and a single data pin. The rest of the connector is just empty plastic. I've drawn out a crude diagram in the other open issue: https://github.com/puddly/casserole/issues/3#issue-433554335

Does yours look different?

**Comment by puddly** [comment]
Here's a picture of what I mean:

![image](https://user-images.githubusercontent.com/32534428/71549130-53697c80-2986-11ea-91ac-5b9bad66e2d5.png)
